export class Continents{

continent_map:any= [
    {
      continent: 'Oceania',
      countries: ['Australia', 'Fiji'],
    },
    {
      continent: 'Europe',
      countries: [
        'Anguilla',
        'Aruba',
        'Austria',
        'Azerbaijan',
        'Belgium',
        'Bulgaria',
        'Croatia',
        'Curacao',
        'Cyprus',
        'Denmark',
        'Finland',
        'France',
        'Georgia',
        'Germany',
        'Greece',
        'Italy',
        'Luxembourg',
        'Malta',
        'Monaco',
        'Netherlands',
        'Netherlands Antilles',
        'Norway',
        'Poland',
        'Portugal',
        'Romania',
        'Spain',
        'Sweden',
        'Switzerland',
        'Ukraine',
        'United Kingdom',
      ],
    },
    {
      continent: 'Usa',
      countries: [
        
        'Virginia',
        'Pennsylvania',
        'Georgia',
        'Maryland',
        'Massachussetts',
        'Connecticut',
        'South Carolina',
        'Florida',
        'New Jersey',
        'North Carolina',
        'New York',
        'District of Columbia',
        'Delaware',
      ],
    },
    {
      continent: 'Usa1',
      countries: [
        'United States',
        'Alaska',
        'Arizona',
        'California',
        'Colorado',
        'Hawaii',
        'Idaho',
        'Montana',
        'Nevada',
        'New Mexico',
        'Oregon',
        'Utah',
        'Washington',
        'Wyoming',
      ],
    },
  ];
}