name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependecies
      run: npm install

    - name: Build
      run: npm run build

    - name: Copy into s3 bucket
      run: aws s3 sync build/ s3://$HOSTING_BUCKET/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.REGION }}
        HOSTING_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}