name: Node.js CI

on:
  push:
    branches: [ dev ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1            
      env: 
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
        AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
        AWS_REGION: eu-west-1  
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: aws s3 sync ./build s3://$AWS_S3_BUCKET       
          